### ISSUE TITLE
Tests fail with msg

### ISSUE THREAD

**Issue by wasowski** [gavanderhoorn/rosin_bug_hunt_l3#6]
This is the result of running `catkin_make run_tests_tf2_ros`, just the very end of the log. There is some problem with `msg`.  @gavanderhoorn, can you quickly assess whether this is a problem with tf2 to tests, or perhaps this is an obvious problem with our build setup? Or perhaps a nonobvious one ...

```
...
Scanning dependencies of target run_tests_tf2_ros_rostest_test_transform_listener_time_reset_test.launch
Scanning dependencies of target run_tests_tf2_ros_rostest_test_transform_listener_unittest.launch
-- run_tests.py: execute commands
  /ros_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/ros_ws/src/geometry2/tf2_ros --package=tf2_ros --results-filename test_transform_listener_time_reset_test.xml --results-base-dir /ros_ws/build/test_results /ros_ws/src/geometry2/tf2_ros/test/transform_listener_time_reset_test.launch 
-- run_tests.py: execute commands
  /ros_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/ros_ws/src/geometry2/tf2_ros --package=tf2_ros --results-filename test_transform_listener_unittest.xml --results-base-dir /ros_ws/build/test_results /ros_ws/src/geometry2/tf2_ros/test/transform_listener_unittest.launch 
Traceback (most recent call last):
  File "/ros_ws/src/ros_comm/rostest/scripts/rostest", line 36, in <module>
    rostestmain()
  File "<string>", line 272, in rostestmain
  File "/ros_ws/src/ros_comm/rostest/src/rostest/rostest_main.py", line 46, in <module>
    import roslaunch
  File "/ros_ws/devel/lib/python2.7/dist-packages/roslaunch/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 61, in <module>
  File "/ros_ws/src/ros_comm/roslaunch/src/roslaunch/scriptapi.py", line 42, in <module>
    import roslaunch.parent
  File "/ros_ws/src/ros_comm/roslaunch/src/roslaunch/parent.py", line 54, in <module>
    import roslaunch.server
  File "/ros_ws/src/ros_comm/roslaunch/src/roslaunch/server.py", line 78, in <module>
    from rosgraph_msgs.msg import Log
ImportError: No module named msg
Traceback (most recent call last):
  File "/ros_ws/src/ros_comm/rostest/scripts/rostest", line 36, in <module>
    rostestmain()
  File "<string>", line 272, in rostestmain
  File "/ros_ws/src/ros_comm/rostest/src/rostest/rostest_main.py", line 46, in <module>
    import roslaunch
  File "/ros_ws/devel/lib/python2.7/dist-packages/roslaunch/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 61, in <module>
  File "/ros_ws/src/ros_comm/roslaunch/src/roslaunch/scriptapi.py", line 42, in <module>
    import roslaunch.parent
  File "/ros_ws/src/ros_comm/roslaunch/src/roslaunch/parent.py", line 54, in <module>
    import roslaunch.server
  File "/ros_ws/src/ros_comm/roslaunch/src/roslaunch/server.py", line 78, in <module>
    from rosgraph_msgs.msg import Log
ImportError: No module named msg
-- run_tests.py: verify result "/ros_ws/build/test_results/tf2_ros/rostest-test_transform_listener_time_reset_test.xml"
Cannot find results, writing failure results to '/ros_ws/build/test_results/tf2_ros/MISSING-rostest-test_transform_listener_time_reset_test.xml'
-- run_tests.py: verify result "/ros_ws/build/test_results/tf2_ros/rostest-test_transform_listener_unittest.xml"
Cannot find results, writing failure results to '/ros_ws/build/test_results/tf2_ros/MISSING-rostest-test_transform_listener_unittest.xml'
Built target run_tests_tf2_ros_rostest_test_transform_listener_time_reset_test.launch
Built target run_tests_tf2_ros_rostest_test_transform_listener_unittest.launch
```

**Comment by gavanderhoorn** [comment]
Is this with or without the `build` and `devel` spaces present in the image?

**Comment by wasowski** [comment]
This is with both `build` and `devel` spaces in the image, and I have sourced `devel/setup.bash` (more precisely `devel_isolated/setup.bash`).

**Comment by gavanderhoorn** [comment]
I believe you've just rebuilt the entire workspace with `catkin_make`, instead of `catkin_make_isolated`.

If I run this:

```
catkin_make_isolated --pkg tf2_ros --make-args run_tests
```

I get the following output (abbreviated):

```
[...]

[ROSTEST]-----------------------------------------------------------------------

[tf2_ros.rosunit-transform_listener_time_reset_test/time_backwards][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 0

-- run_tests.py: verify result "/ros_ws/build_isolated/tf2_ros/test_results/tf2_ros/rostest-test_transform_listener_time_reset_test.xml"
[100%] Built target _run_tests_tf2_ros_rostest_test_transform_listener_time_reset_test.launch
Scanning dependencies of target _run_tests_tf2_ros_rostest
[100%] Built target _run_tests_tf2_ros_rostest
Scanning dependencies of target _run_tests_tf2_ros
[100%] Built target _run_tests_tf2_ros
Scanning dependencies of target run_tests
[100%] Built target run_tests
<== Finished processing package [44 of 44]: 'tf2_ros'
```

and `catkin_test_results` reports:

```
Summary: 4 tests, 0 errors, 0 failures
```

**Comment by wasowski** [comment]
So the answer is not to run tests with catkin_make, but with catkin_make_isolated? 
When I do this (as you suggested above), I am getting a well-formatted output (similar to yours), except that I have one failure.  

Q. How do I get test results with catkin_make_isolated ?

Disclaimer: I only now start to understand your scripts a bit better, and I realize that I might have done things very wrongly.  First, I never noticed the TODO section :) (that file leaves on a branch). Second, I have build my images using your Dockerfile (I scrapped mine; yours was better). Only now I realized that you actually had a wrapper script for that build which does other things.  I am investigating that wrapper script, which might have some explanations for the errors I am seeing.

**Comment by gavanderhoorn** [comment]
Sort of.

This is a consequence of us doing a source install (which includes the non-catkin package: `catkin` (yes, I know)). `catkin_make` cannot build workspaces that have non-catkin pkgs in them (don't ask), so that's why we use `catkin_make_isolated`.

I'm a little confused as to what actually happened for you, as `catkin_make` should actually complain you have some non-catkin packages in there and refuse to do anything.

**Comment by gavanderhoorn** [comment]
I'm not too happy with this setup (`catkin_make`, `catkin_make_isolated`, etc). I'll see if I can come up with something a little more streamlined next week or something.

**Comment by wasowski** [comment]
Oops. Just realized that the timemachine branch actually has a simple container build setup (like I used). I think it was a red herring to look at the master.  Is there any reason why you would not merge it into master?

**Comment by gavanderhoorn** [comment]
O you weren't using the `l3_time_machine_tf2_ros` branch?

**Comment by wasowski** [comment]
Not really (blush)
